#cloud-config
ssh_authorized_keys:
    - ${pubkey}

hostname: ${hostname}
fqdn: ${fqdn}
manage_etc_hosts: true

timezone: Europe/Moscow

packages:
    - python3-minimal
    - qemu-guest-agent

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, qemu-guest-agent.service ]
  - [ systemctl, start, qemu-guest-agent.service ]
